// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: pic.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetPicInfoByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPicInfoByIdRequest) Reset() {
	*x = GetPicInfoByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPicInfoByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPicInfoByIdRequest) ProtoMessage() {}

func (x *GetPicInfoByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPicInfoByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPicInfoByIdRequest) Descriptor() ([]byte, []int) {
	return file_pic_proto_rawDescGZIP(), []int{0}
}

func (x *GetPicInfoByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPicInfoByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetPicInfoByIdResponse) Reset() {
	*x = GetPicInfoByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPicInfoByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPicInfoByIdResponse) ProtoMessage() {}

func (x *GetPicInfoByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPicInfoByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPicInfoByIdResponse) Descriptor() ([]byte, []int) {
	return file_pic_proto_rawDescGZIP(), []int{1}
}

func (x *GetPicInfoByIdResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPicInfoByIdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPicInfoByIdResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_pic_proto protoreflect.FileDescriptor

var file_pic_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x69, 0x63,
	0x2e, 0x76, 0x31, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x69, 0x63, 0x49, 0x6e, 0x66,
	0x6f, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4e, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x50, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x32, 0x58, 0x0a, 0x03,
	0x50, 0x69, 0x63, 0x12, 0x51, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x69, 0x63, 0x49, 0x6e, 0x66,
	0x6f, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x2e, 0x70, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x57, 0x65, 0x65, 0x6b, 0x30, 0x34,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pic_proto_rawDescOnce sync.Once
	file_pic_proto_rawDescData = file_pic_proto_rawDesc
)

func file_pic_proto_rawDescGZIP() []byte {
	file_pic_proto_rawDescOnce.Do(func() {
		file_pic_proto_rawDescData = protoimpl.X.CompressGZIP(file_pic_proto_rawDescData)
	})
	return file_pic_proto_rawDescData
}

var file_pic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pic_proto_goTypes = []interface{}{
	(*GetPicInfoByIdRequest)(nil),  // 0: pic.v1.GetPicInfoByIdRequest
	(*GetPicInfoByIdResponse)(nil), // 1: pic.v1.GetPicInfoByIdResponse
}
var file_pic_proto_depIdxs = []int32{
	0, // 0: pic.v1.Pic.GetPicInfoById:input_type -> pic.v1.GetPicInfoByIdRequest
	1, // 1: pic.v1.Pic.GetPicInfoById:output_type -> pic.v1.GetPicInfoByIdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pic_proto_init() }
func file_pic_proto_init() {
	if File_pic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPicInfoByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPicInfoByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pic_proto_goTypes,
		DependencyIndexes: file_pic_proto_depIdxs,
		MessageInfos:      file_pic_proto_msgTypes,
	}.Build()
	File_pic_proto = out.File
	file_pic_proto_rawDesc = nil
	file_pic_proto_goTypes = nil
	file_pic_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PicClient is the client API for Pic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PicClient interface {
	GetPicInfoById(ctx context.Context, in *GetPicInfoByIdRequest, opts ...grpc.CallOption) (*GetPicInfoByIdResponse, error)
}

type picClient struct {
	cc grpc.ClientConnInterface
}

func NewPicClient(cc grpc.ClientConnInterface) PicClient {
	return &picClient{cc}
}

func (c *picClient) GetPicInfoById(ctx context.Context, in *GetPicInfoByIdRequest, opts ...grpc.CallOption) (*GetPicInfoByIdResponse, error) {
	out := new(GetPicInfoByIdResponse)
	err := c.cc.Invoke(ctx, "/pic.v1.Pic/GetPicInfoById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PicServer is the server API for Pic service.
type PicServer interface {
	GetPicInfoById(context.Context, *GetPicInfoByIdRequest) (*GetPicInfoByIdResponse, error)
}

// UnimplementedPicServer can be embedded to have forward compatible implementations.
type UnimplementedPicServer struct {
}

func (*UnimplementedPicServer) GetPicInfoById(context.Context, *GetPicInfoByIdRequest) (*GetPicInfoByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPicInfoById not implemented")
}

func RegisterPicServer(s *grpc.Server, srv PicServer) {
	s.RegisterService(&_Pic_serviceDesc, srv)
}

func _Pic_GetPicInfoById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPicInfoByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PicServer).GetPicInfoById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pic.v1.Pic/GetPicInfoById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PicServer).GetPicInfoById(ctx, req.(*GetPicInfoByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pic.v1.Pic",
	HandlerType: (*PicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPicInfoById",
			Handler:    _Pic_GetPicInfoById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pic.proto",
}
